# fly.toml app configuration file generated for werewolves-road-wispy-violet-795 on 2025-07-28T21:58:11+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "werewolves-game"
primary_region = "lhr" # London region, but you can change this

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  NODE_ENV = "production"
  HOST = "0.0.0.0"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[mounts]
  source="werewolves_data"
  destination="/data"
