#!/bin/bash

echo "🚀 Setting up Netlify Environment Variables"
echo ""
echo "Please add these environment variables to your Netlify dashboard:"
echo ""
echo "1. Go to: https://app.netlify.com/sites/werewolves-road/settings/env"
echo "2. Click 'Add a variable' for each of the following:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Variable 1:"
echo "Key:   VITE_SUPABASE_URL"
echo "Value: https://lfexxmccwzfvlmwgqgdq.supabase.co"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Variable 2:"
echo "Key:   VITE_SUPABASE_ANON_KEY"
echo "Value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmZXh4bWNjd3pmdmxtd2dxZ2RxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc5MTE2MjksImV4cCI6MjA4MzQ4NzYyOX0.aRwqQJqgGRctamHTGsHCdRbjDdWrRXKWU4J475elr5M"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "3. Click 'Save' after adding both variables"
echo "4. Trigger a new deploy: Deploys → Trigger deploy → Deploy site"
echo ""
echo "✅ Once deployed, your site will be able to connect to Supabase!"
